windowrule { 
  name = ignore-max
  match:class = .*
  suppress_event = maximize
}

windowrule { 
  name = xwayland-drag-fix
  match:class = ^$
  match:title = ^$
  match:xwayland = 1
  match:float = 1

  no_focus = true
}

windowrule { 
  name = discord
  match:class = ^(discord)$

  workspace = 10
}

windowrule {
  name = ueberzugpp
  match:class = ^ueberzugpp_.*
  match:title = ^ueberzugpp_.*

  float = true
  pin = true
  move = ((monitor_w-window_w)-10) 10
  no_focus = true
}
